import type { Theme } from '../theme-types'

export const catppuccinMocha: Theme = {
    name: 'catppuccin-mocha',
    displayName: 'Catppuccin Mocha',
    palette: {
        red: '#F38BA8',
        orange: '#FAB387',
        yellow: '#F9E2AF',
        green: '#A6E3A1',
        cyan: '#94E2D5',
        blue: '#89B4FA',
        purple: '#CBA6F7',
        pink: '#F5C2E7',
        white: '#F5E0DC',
        gray: '#9399B2',
        text: '#BAC2DE',
        textMuted: '#A6ADC8',
        surface: '#585B70',
        surfaceBright: '#45475A',
        surfaceDim: '#313244',
    },
    semantic: {
        primary: 'blue',
        secondary: 'cyan',
        accent: 'purple',
        success: 'green',
        warning: 'yellow',
        error: 'red',
        info: 'cyan',
        muted: 'gray',
        highlight: 'purple',
    },
    gitFormat: {
        key: 'blue',
        date: 'cyan',
        author: 'purple',
        email: 'green',
        text: 'text',
        hash: 'yellow',
        add: 'green',
        remove: 'red',
        change: 'yellow',
        path: 'purple',
        num: 'blue',
        oldHash: 'cyan',
        newHash: 'green',
        tag: 'pink',
    },
    diff: {
        oldRowNo: 'yellow',
        newRowNo: 'cyan',
        text: 'text',
    },
    box: {
        title: 'purple',
        border: 'gray',
    },
    display: {
        note: 'cyan',
        important: 'pink',
        tip: 'green',
        success: 'green',
        caution: 'purple',
        warning: 'orange',
        error: 'red',
        highlight: 'purple',
    },
}

export const rosePine: Theme = {
    name: 'rose-pine',
    displayName: 'Rose Pine',
    palette: {
        red: '#eb6f92',
        orange: '#f6c177',
        yellow: '#f6c177',
        green: '#9ccfd8',
        cyan: '#9ccfd8',
        blue: '#c4a7e7',
        purple: '#c4a7e7',
        pink: '#eb6f92',
        white: '#e0def4',
        gray: '#6e6a86',
        text: '#e0def4',
        textMuted: '#908caa',
        surface: '#26233a',
        surfaceBright: '#403d52',
        surfaceDim: '#191724',
    },
    semantic: {
        primary: 'blue',
        secondary: 'cyan',
        accent: 'purple',
        success: 'green',
        warning: 'yellow',
        error: 'red',
        info: 'cyan',
        muted: 'gray',
        highlight: 'purple',
    },
    gitFormat: {
        key: 'blue',
        date: 'cyan',
        author: 'purple',
        email: 'green',
        text: 'text',
        hash: 'yellow',
        add: 'green',
        remove: 'red',
        change: 'yellow',
        path: 'purple',
        num: 'blue',
        oldHash: 'cyan',
        newHash: 'green',
        tag: 'pink',
    },
    diff: {
        oldRowNo: 'yellow',
        newRowNo: 'cyan',
        text: 'text',
    },
    box: {
        title: 'purple',
        border: 'gray',
    },
    display: {
        note: 'cyan',
        important: 'pink',
        tip: 'green',
        success: 'green',
        caution: 'purple',
        warning: 'orange',
        error: 'red',
        highlight: 'purple',
    },
}

export const tokyoNight: Theme = {
    name: 'tokyonight',
    displayName: 'Tokyo Night',
    palette: {
        red: '#f7768e',
        orange: '#ff9e64',
        yellow: '#e0af68',
        green: '#9ece6a',
        cyan: '#7dcfff',
        blue: '#7aa2f7',
        purple: '#bb9af7',
        pink: '#f7768e',
        white: '#c0caf5',
        gray: '#565f89',
        text: '#a9b1d6',
        textMuted: '#787c99',
        surface: '#3b4261',
        surfaceBright: '#565f89',
        surfaceDim: '#1a1b26',
    },
    semantic: {
        primary: 'blue',
        secondary: 'cyan',
        accent: 'purple',
        success: 'green',
        warning: 'yellow',
        error: 'red',
        info: 'cyan',
        muted: 'gray',
        highlight: 'purple',
    },
    gitFormat: {
        key: 'blue',
        date: 'cyan',
        author: 'purple',
        email: 'green',
        text: 'text',
        hash: 'yellow',
        add: 'green',
        remove: 'red',
        change: 'yellow',
        path: 'purple',
        num: 'blue',
        oldHash: 'cyan',
        newHash: 'green',
        tag: 'pink',
    },
    diff: {
        oldRowNo: 'yellow',
        newRowNo: 'cyan',
        text: 'text',
    },
    box: {
        title: 'purple',
        border: 'gray',
    },
    display: {
        note: 'cyan',
        important: 'pink',
        tip: 'green',
        success: 'green',
        caution: 'purple',
        warning: 'orange',
        error: 'red',
        highlight: 'purple',
    },
}

export const kanagawa: Theme = {
    name: 'kanagawa',
    displayName: 'Kanagawa',
    palette: {
        red: '#ff5d62',
        orange: '#ffa066',
        yellow: '#e6c384',
        green: '#98bb6c',
        cyan: '#7aa89f',
        blue: '#7e9cd8',
        purple: '#957fb8',
        pink: '#d27e99',
        white: '#dcd7ba',
        gray: '#727169',
        text: '#c8c093',
        textMuted: '#a6a69d',
        surface: '#54546d',
        surfaceBright: '#2a2a37',
        surfaceDim: '#1f1f28',
    },
    semantic: {
        primary: 'blue',
        secondary: 'cyan',
        accent: 'purple',
        success: 'green',
        warning: 'yellow',
        error: 'red',
        info: 'cyan',
        muted: 'gray',
        highlight: 'purple',
    },
    gitFormat: {
        key: 'blue',
        date: 'cyan',
        author: 'purple',
        email: 'green',
        text: 'text',
        hash: 'yellow',
        add: 'green',
        remove: 'red',
        change: 'yellow',
        path: 'purple',
        num: 'blue',
        oldHash: 'cyan',
        newHash: 'green',
        tag: 'pink',
    },
    diff: {
        oldRowNo: 'yellow',
        newRowNo: 'cyan',
        text: 'text',
    },
    box: {
        title: 'purple',
        border: 'gray',
    },
    display: {
        note: 'cyan',
        important: 'pink',
        tip: 'green',
        success: 'green',
        caution: 'purple',
        warning: 'orange',
        error: 'red',
        highlight: 'purple',
    },
}

export const dracula: Theme = {
    name: 'dracula',
    displayName: 'Dracula',
    palette: {
        red: '#ff5555',
        orange: '#ffb86c',
        yellow: '#f1fa8c',
        green: '#50fa7b',
        cyan: '#8be9fd',
        blue: '#8be9fd',
        purple: '#bd93f9',
        pink: '#ff79c6',
        white: '#f8f8f2',
        gray: '#6272a4',
        text: '#f8f8f2',
        textMuted: '#bfbfbf',
        surface: '#44475a',
        surfaceBright: '#6272a4',
        surfaceDim: '#282a36',
    },
    semantic: {
        primary: 'blue',
        secondary: 'cyan',
        accent: 'purple',
        success: 'green',
        warning: 'yellow',
        error: 'red',
        info: 'cyan',
        muted: 'gray',
        highlight: 'purple',
    },
    gitFormat: {
        key: 'blue',
        date: 'cyan',
        author: 'purple',
        email: 'green',
        text: 'text',
        hash: 'yellow',
        add: 'green',
        remove: 'red',
        change: 'yellow',
        path: 'purple',
        num: 'blue',
        oldHash: 'cyan',
        newHash: 'green',
        tag: 'pink',
    },
    diff: {
        oldRowNo: 'yellow',
        newRowNo: 'cyan',
        text: 'text',
    },
    box: {
        title: 'purple',
        border: 'gray',
    },
    display: {
        note: 'cyan',
        important: 'pink',
        tip: 'green',
        success: 'green',
        caution: 'purple',
        warning: 'orange',
        error: 'red',
        highlight: 'purple',
    },
}

export const allThemes: Theme[] = [
    catppuccinMocha,
    rosePine,
    tokyoNight,
    kanagawa,
    dracula,
]

export function getThemeByName(name: string): Theme | undefined {
    return allThemes.find((t) => t.name === name)
}

export function listThemes(): Theme[] {
    return allThemes
}
