import type { Theme } from "./theme-types"

export const catppuccinMocha: Theme = {
  name: "catppuccin-mocha",
  displayName: "Catppuccin Mocha",
  palette: {
    red: "#F38BA8",
    orange: "#FAB387",
    yellow: "#F9E2AF",
    green: "#A6E3A1",
    cyan: "#94E2D5",
    blue: "#89B4FA",
    purple: "#CBA6F7",
    pink: "#F5C2E7",
    white: "#F5E0DC",
    gray: "#9399B2",
    text: "#BAC2DE",
    textMuted: "#A6ADC8",
    surface: "#585B70",
    surfaceBright: "#45475A",
    surfaceDim: "#313244",
  },
  semantic: {
    primary: "blue",
    secondary: "cyan",
    accent: "purple",
    success: "green",
    warning: "yellow",
    error: "red",
    info: "cyan",
    muted: "gray",
    highlight: "purple",
  },
  gitFormat: {
    key: "blue",
    date: "cyan",
    author: "purple",
    email: "green",
    text: "text",
    hash: "yellow",
    add: "green",
    remove: "red",
    change: "yellow",
    path: "purple",
    num: "blue",
    oldHash: "cyan",
    newHash: "green",
    tag: "pink",
  },
  diff: {
    oldRowNo: "yellow",
    newRowNo: "cyan",
    text: "text",
  },
  box: {
    title: "purple",
    border: "gray",
  },
  display: {
    note: "cyan",
    important: "pink",
    tip: "green",
    success: "green",
    caution: "purple",
    warning: "orange",
    error: "red",
    highlight: "purple",
  },
}
